### ISSUE TITLE
uri.hostname() dosn't work

### ISSUE THREAD

**Issue by mateuszjarzewski** [radmen/miuri.js#5]
Title tell the story.
Tytuł mówi wszystko.
Pozdrowienia z Gdyni ^_^

**Comment by radmen** [comment]
A możesz podać fragment kodu jaki używałeś? Byłoby to pomocne w znalezieniu buga.

**Comment by mateuszjarzewski** [comment]
Nie czaje. Masz błąd w readme, w kodzie jest .host() a w readme .hostname()

``` javascript
$.getScript(
    'http://rawgit.com/radmen/miuri.js/master/lib/miuri.min.js'
).then(function(){
    var host
    host = new miuri('http://google.com/').hostname() // fail
    host = new miuri('http://google.com/').host() // OK
})  
```

**Comment by radmen** [comment]
> Nie czaje. Masz błąd w readme, w kodzie jest .host() a w readme .hostname()

Napisałeś, że metoda nie działa. Nie wskazałeś, że błąd jest w pliku READMe.

**Comment by mateuszjarzewski** [comment]
Bo założyłem, że nie nie trzeba dużo myślenia aby rozszyfrować "uri.hostname() dosn't work".

**Comment by radmen** [comment]
Stwierdzenie "nie działa" oznacza wiele rzeczy - błąd składni, nieprawidłowy wynik wykonania, brak dokumentacji, błąd w dokumentacji, brak metody etc. Nie jestem od tego aby zgadywać co miałeś na myśli.

**Comment by mateuszjarzewski** [comment]
Nie trzeba zgadywać, wystarczy odpalić "uri.hostname()".

**Comment by radmen** [comment]
> Nie trzeba zgadywać, wystarczy odpalić "uri.hostname()".

To by mi powiedziało jedynie o tym, że nie ma takiej metody. Nie wskazuje to na to, że błąd jest w dokumentacji.

Zgłaszane błędy powinny być opisywane możliwie dokładnie. Jeśli tak nie jest dopytuję zanim zacznę sprawdzać co nie działa (zwyczajnie nie mam czasu na takie rzeczy). Ta zasada dotyczy również takich malutkich projektów jak `miuri.js`.
